//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Logstashconfig.g4 by ANTLR 4.5.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LogstashconfigParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.2")]
[System.CLSCompliant(false)]
public interface ILogstashconfigVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfig([NotNull] LogstashconfigParser.ConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.stage_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStage_declaration([NotNull] LogstashconfigParser.Stage_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.stage_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStage_definition([NotNull] LogstashconfigParser.Stage_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.plugin_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlugin_declaration([NotNull] LogstashconfigParser.Plugin_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.plugin_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlugin_definition([NotNull] LogstashconfigParser.Plugin_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.plugin_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlugin_attribute([NotNull] LogstashconfigParser.Plugin_attributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.plugin_attribute_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlugin_attribute_value([NotNull] LogstashconfigParser.Plugin_attribute_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.stage_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStage_condition([NotNull] LogstashconfigParser.Stage_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.logical_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_expression([NotNull] LogstashconfigParser.Logical_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.negative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegative_expression([NotNull] LogstashconfigParser.Negative_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.compare_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare_expression([NotNull] LogstashconfigParser.Compare_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.in_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_expression([NotNull] LogstashconfigParser.In_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.match_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatch_expression([NotNull] LogstashconfigParser.Match_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.rvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRvalue([NotNull] LogstashconfigParser.RvalueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.fieldref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldref([NotNull] LogstashconfigParser.FieldrefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.fieldref_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldref_element([NotNull] LogstashconfigParser.Fieldref_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] LogstashconfigParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.array_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_element([NotNull] LogstashconfigParser.Array_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.hash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHash([NotNull] LogstashconfigParser.HashContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.hash_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHash_element([NotNull] LogstashconfigParser.Hash_elementContext context);
}
