//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Logstashconfig.g4 by ANTLR 4.5.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


  


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILogstashconfigListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.2")]
[System.CLSCompliant(false)]
public partial class LogstashconfigBaseListener : ILogstashconfigListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfig([NotNull] LogstashconfigParser.ConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfig([NotNull] LogstashconfigParser.ConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.filler"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFiller([NotNull] LogstashconfigParser.FillerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.filler"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFiller([NotNull] LogstashconfigParser.FillerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] LogstashconfigParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] LogstashconfigParser.CommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlugin_section([NotNull] LogstashconfigParser.Plugin_sectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin_section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlugin_section([NotNull] LogstashconfigParser.Plugin_sectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlugin_type([NotNull] LogstashconfigParser.Plugin_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlugin_type([NotNull] LogstashconfigParser.Plugin_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.branch_or_plugin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBranch_or_plugin([NotNull] LogstashconfigParser.Branch_or_pluginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.branch_or_plugin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBranch_or_plugin([NotNull] LogstashconfigParser.Branch_or_pluginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.branch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBranch([NotNull] LogstashconfigParser.BranchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.branch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBranch([NotNull] LogstashconfigParser.BranchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlugin([NotNull] LogstashconfigParser.PluginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlugin([NotNull] LogstashconfigParser.PluginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.attributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributes([NotNull] LogstashconfigParser.AttributesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.attributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributes([NotNull] LogstashconfigParser.AttributesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] LogstashconfigParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] LogstashconfigParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.r_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR_if([NotNull] LogstashconfigParser.R_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.r_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR_if([NotNull] LogstashconfigParser.R_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.else_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_if([NotNull] LogstashconfigParser.Else_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.else_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_if([NotNull] LogstashconfigParser.Else_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.r_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR_else([NotNull] LogstashconfigParser.R_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.r_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR_else([NotNull] LogstashconfigParser.R_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] LogstashconfigParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] LogstashconfigParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] LogstashconfigParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] LogstashconfigParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.single_quoted_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_quoted_string([NotNull] LogstashconfigParser.Single_quoted_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.single_quoted_string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_quoted_string([NotNull] LogstashconfigParser.Single_quoted_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] LogstashconfigParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] LogstashconfigParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] LogstashconfigParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] LogstashconfigParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] LogstashconfigParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] LogstashconfigParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] LogstashconfigParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] LogstashconfigParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] LogstashconfigParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] LogstashconfigParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.hash"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHash([NotNull] LogstashconfigParser.HashContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.hash"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHash([NotNull] LogstashconfigParser.HashContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.hashentries"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHashentries([NotNull] LogstashconfigParser.HashentriesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.hashentries"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHashentries([NotNull] LogstashconfigParser.HashentriesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.hashentry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHashentry([NotNull] LogstashconfigParser.HashentryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.hashentry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHashentry([NotNull] LogstashconfigParser.HashentryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.boolean_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_operator([NotNull] LogstashconfigParser.Boolean_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.boolean_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_operator([NotNull] LogstashconfigParser.Boolean_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.negative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegative_expression([NotNull] LogstashconfigParser.Negative_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.negative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegative_expression([NotNull] LogstashconfigParser.Negative_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.in_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIn_expression([NotNull] LogstashconfigParser.In_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.in_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIn_expression([NotNull] LogstashconfigParser.In_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.not_in_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_in_expression([NotNull] LogstashconfigParser.Not_in_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.not_in_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_in_expression([NotNull] LogstashconfigParser.Not_in_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.rvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRvalue([NotNull] LogstashconfigParser.RvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.rvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRvalue([NotNull] LogstashconfigParser.RvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector([NotNull] LogstashconfigParser.SelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector([NotNull] LogstashconfigParser.SelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.compare_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompare_expression([NotNull] LogstashconfigParser.Compare_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.compare_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompare_expression([NotNull] LogstashconfigParser.Compare_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.regexp_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegexp_expression([NotNull] LogstashconfigParser.Regexp_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.regexp_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegexp_expression([NotNull] LogstashconfigParser.Regexp_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.selector_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector_element([NotNull] LogstashconfigParser.Selector_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.selector_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector_element([NotNull] LogstashconfigParser.Selector_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.in_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIn_operator([NotNull] LogstashconfigParser.In_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.in_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIn_operator([NotNull] LogstashconfigParser.In_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.not_in_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_in_operator([NotNull] LogstashconfigParser.Not_in_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.not_in_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_in_operator([NotNull] LogstashconfigParser.Not_in_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.method_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_call([NotNull] LogstashconfigParser.Method_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.method_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_call([NotNull] LogstashconfigParser.Method_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.regexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegexp([NotNull] LogstashconfigParser.RegexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.regexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegexp([NotNull] LogstashconfigParser.RegexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.compare_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompare_operator([NotNull] LogstashconfigParser.Compare_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.compare_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompare_operator([NotNull] LogstashconfigParser.Compare_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.regexp_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegexp_operator([NotNull] LogstashconfigParser.Regexp_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.regexp_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegexp_operator([NotNull] LogstashconfigParser.Regexp_operatorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
