//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Logstashconfig.g4 by ANTLR 4.5.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILogstashconfigListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.2")]
[System.CLSCompliant(false)]
public partial class LogstashconfigBaseListener : ILogstashconfigListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfig([NotNull] LogstashconfigParser.ConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfig([NotNull] LogstashconfigParser.ConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.stage_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStage_declaration([NotNull] LogstashconfigParser.Stage_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.stage_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStage_declaration([NotNull] LogstashconfigParser.Stage_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.stage_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStage_definition([NotNull] LogstashconfigParser.Stage_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.stage_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStage_definition([NotNull] LogstashconfigParser.Stage_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlugin_declaration([NotNull] LogstashconfigParser.Plugin_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlugin_declaration([NotNull] LogstashconfigParser.Plugin_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlugin_definition([NotNull] LogstashconfigParser.Plugin_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlugin_definition([NotNull] LogstashconfigParser.Plugin_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin_attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlugin_attribute([NotNull] LogstashconfigParser.Plugin_attributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin_attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlugin_attribute([NotNull] LogstashconfigParser.Plugin_attributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin_attribute_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlugin_attribute_value([NotNull] LogstashconfigParser.Plugin_attribute_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin_attribute_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlugin_attribute_value([NotNull] LogstashconfigParser.Plugin_attribute_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.stage_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStage_condition([NotNull] LogstashconfigParser.Stage_conditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.stage_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStage_condition([NotNull] LogstashconfigParser.Stage_conditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.logical_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_expression([NotNull] LogstashconfigParser.Logical_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.logical_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_expression([NotNull] LogstashconfigParser.Logical_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.negative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegative_expression([NotNull] LogstashconfigParser.Negative_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.negative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegative_expression([NotNull] LogstashconfigParser.Negative_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.compare_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompare_expression([NotNull] LogstashconfigParser.Compare_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.compare_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompare_expression([NotNull] LogstashconfigParser.Compare_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.in_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIn_expression([NotNull] LogstashconfigParser.In_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.in_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIn_expression([NotNull] LogstashconfigParser.In_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.match_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatch_expression([NotNull] LogstashconfigParser.Match_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.match_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatch_expression([NotNull] LogstashconfigParser.Match_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.rvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRvalue([NotNull] LogstashconfigParser.RvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.rvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRvalue([NotNull] LogstashconfigParser.RvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.fieldref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldref([NotNull] LogstashconfigParser.FieldrefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.fieldref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldref([NotNull] LogstashconfigParser.FieldrefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.fieldref_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldref_element([NotNull] LogstashconfigParser.Fieldref_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.fieldref_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldref_element([NotNull] LogstashconfigParser.Fieldref_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] LogstashconfigParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] LogstashconfigParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.array_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_element([NotNull] LogstashconfigParser.Array_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.array_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_element([NotNull] LogstashconfigParser.Array_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.hash"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHash([NotNull] LogstashconfigParser.HashContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.hash"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHash([NotNull] LogstashconfigParser.HashContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.hash_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHash_element([NotNull] LogstashconfigParser.Hash_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.hash_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHash_element([NotNull] LogstashconfigParser.Hash_elementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
