//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Logstashconfig.g4 by ANTLR 4.5.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


  

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LogstashconfigParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.2")]
[System.CLSCompliant(false)]
public interface ILogstashconfigListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConfig([NotNull] LogstashconfigParser.ConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConfig([NotNull] LogstashconfigParser.ConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.filler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFiller([NotNull] LogstashconfigParser.FillerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.filler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFiller([NotNull] LogstashconfigParser.FillerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] LogstashconfigParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] LogstashconfigParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlugin_section([NotNull] LogstashconfigParser.Plugin_sectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlugin_section([NotNull] LogstashconfigParser.Plugin_sectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlugin_type([NotNull] LogstashconfigParser.Plugin_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlugin_type([NotNull] LogstashconfigParser.Plugin_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.branch_or_plugin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBranch_or_plugin([NotNull] LogstashconfigParser.Branch_or_pluginContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.branch_or_plugin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBranch_or_plugin([NotNull] LogstashconfigParser.Branch_or_pluginContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBranch([NotNull] LogstashconfigParser.BranchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBranch([NotNull] LogstashconfigParser.BranchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.plugin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlugin([NotNull] LogstashconfigParser.PluginContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.plugin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlugin([NotNull] LogstashconfigParser.PluginContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributes([NotNull] LogstashconfigParser.AttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributes([NotNull] LogstashconfigParser.AttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] LogstashconfigParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] LogstashconfigParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.r_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR_if([NotNull] LogstashconfigParser.R_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.r_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR_if([NotNull] LogstashconfigParser.R_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_if([NotNull] LogstashconfigParser.Else_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_if([NotNull] LogstashconfigParser.Else_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.r_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR_else([NotNull] LogstashconfigParser.R_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.r_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR_else([NotNull] LogstashconfigParser.R_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] LogstashconfigParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] LogstashconfigParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] LogstashconfigParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] LogstashconfigParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.single_quoted_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_quoted_string([NotNull] LogstashconfigParser.Single_quoted_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.single_quoted_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_quoted_string([NotNull] LogstashconfigParser.Single_quoted_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] LogstashconfigParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] LogstashconfigParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] LogstashconfigParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] LogstashconfigParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] LogstashconfigParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] LogstashconfigParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] LogstashconfigParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] LogstashconfigParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] LogstashconfigParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] LogstashconfigParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.hash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHash([NotNull] LogstashconfigParser.HashContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.hash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHash([NotNull] LogstashconfigParser.HashContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.hashentries"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHashentries([NotNull] LogstashconfigParser.HashentriesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.hashentries"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHashentries([NotNull] LogstashconfigParser.HashentriesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.hashentry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHashentry([NotNull] LogstashconfigParser.HashentryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.hashentry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHashentry([NotNull] LogstashconfigParser.HashentryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.boolean_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_operator([NotNull] LogstashconfigParser.Boolean_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.boolean_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_operator([NotNull] LogstashconfigParser.Boolean_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.negative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegative_expression([NotNull] LogstashconfigParser.Negative_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.negative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegative_expression([NotNull] LogstashconfigParser.Negative_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.in_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIn_expression([NotNull] LogstashconfigParser.In_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.in_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIn_expression([NotNull] LogstashconfigParser.In_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.not_in_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot_in_expression([NotNull] LogstashconfigParser.Not_in_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.not_in_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot_in_expression([NotNull] LogstashconfigParser.Not_in_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.rvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRvalue([NotNull] LogstashconfigParser.RvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.rvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRvalue([NotNull] LogstashconfigParser.RvalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector([NotNull] LogstashconfigParser.SelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector([NotNull] LogstashconfigParser.SelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.compare_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompare_expression([NotNull] LogstashconfigParser.Compare_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.compare_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompare_expression([NotNull] LogstashconfigParser.Compare_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.regexp_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexp_expression([NotNull] LogstashconfigParser.Regexp_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.regexp_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexp_expression([NotNull] LogstashconfigParser.Regexp_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.selector_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector_element([NotNull] LogstashconfigParser.Selector_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.selector_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector_element([NotNull] LogstashconfigParser.Selector_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.in_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIn_operator([NotNull] LogstashconfigParser.In_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.in_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIn_operator([NotNull] LogstashconfigParser.In_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.not_in_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot_in_operator([NotNull] LogstashconfigParser.Not_in_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.not_in_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot_in_operator([NotNull] LogstashconfigParser.Not_in_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_call([NotNull] LogstashconfigParser.Method_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_call([NotNull] LogstashconfigParser.Method_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.regexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexp([NotNull] LogstashconfigParser.RegexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.regexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexp([NotNull] LogstashconfigParser.RegexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.compare_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompare_operator([NotNull] LogstashconfigParser.Compare_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.compare_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompare_operator([NotNull] LogstashconfigParser.Compare_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LogstashconfigParser.regexp_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexp_operator([NotNull] LogstashconfigParser.Regexp_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LogstashconfigParser.regexp_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexp_operator([NotNull] LogstashconfigParser.Regexp_operatorContext context);
}
