//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Logstashconfig.g4 by ANTLR 4.5.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


  

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LogstashconfigParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.2")]
[System.CLSCompliant(false)]
public interface ILogstashconfigVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfig([NotNull] LogstashconfigParser.ConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.filler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFiller([NotNull] LogstashconfigParser.FillerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] LogstashconfigParser.CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.plugin_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlugin_section([NotNull] LogstashconfigParser.Plugin_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.plugin_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlugin_type([NotNull] LogstashconfigParser.Plugin_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.branch_or_plugin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBranch_or_plugin([NotNull] LogstashconfigParser.Branch_or_pluginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBranch([NotNull] LogstashconfigParser.BranchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.plugin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlugin([NotNull] LogstashconfigParser.PluginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] LogstashconfigParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] LogstashconfigParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.r_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR_if([NotNull] LogstashconfigParser.R_ifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.else_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_if([NotNull] LogstashconfigParser.Else_ifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.r_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR_else([NotNull] LogstashconfigParser.R_elseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] LogstashconfigParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] LogstashconfigParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.single_quoted_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_quoted_string([NotNull] LogstashconfigParser.Single_quoted_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] LogstashconfigParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] LogstashconfigParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] LogstashconfigParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] LogstashconfigParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] LogstashconfigParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.hash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHash([NotNull] LogstashconfigParser.HashContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.hashentries"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHashentries([NotNull] LogstashconfigParser.HashentriesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.hashentry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHashentry([NotNull] LogstashconfigParser.HashentryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.boolean_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_operator([NotNull] LogstashconfigParser.Boolean_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.negative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegative_expression([NotNull] LogstashconfigParser.Negative_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.in_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_expression([NotNull] LogstashconfigParser.In_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.not_in_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_in_expression([NotNull] LogstashconfigParser.Not_in_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.rvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRvalue([NotNull] LogstashconfigParser.RvalueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector([NotNull] LogstashconfigParser.SelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.compare_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare_expression([NotNull] LogstashconfigParser.Compare_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.regexp_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegexp_expression([NotNull] LogstashconfigParser.Regexp_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.selector_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector_element([NotNull] LogstashconfigParser.Selector_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.in_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_operator([NotNull] LogstashconfigParser.In_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.not_in_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_in_operator([NotNull] LogstashconfigParser.Not_in_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_call([NotNull] LogstashconfigParser.Method_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.regexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegexp([NotNull] LogstashconfigParser.RegexpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.compare_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare_operator([NotNull] LogstashconfigParser.Compare_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LogstashconfigParser.regexp_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegexp_operator([NotNull] LogstashconfigParser.Regexp_operatorContext context);
}
